"""
Text3Database - Generowanie schematów baz danych i migracji.

Automatyczne generowanie SQL, NoSQL schemas, migrations.
"""

from typing import Dict, Any, Optional, List
from nlp2cmd.core.base import BaseConverter, ConversionResult
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


class Text3Database(BaseConverter):
    """
    Generator schematów baz danych i migracji.
    
    Obsługuje:
    - PostgreSQL, MySQL, SQLite
    - MongoDB
    - Schema generation
    - Migrations
    - Seed data
    """
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
    
    def parse_intent(self, text: str) -> Dict[str, Any]:
        """
        Parsuje intencję z tekstu.
        
        Returns:
            {
                "db_type": str,       # postgres, mysql, mongodb
                "action": str,        # schema, migration, seed
                "tables": List[str]
            }
        """
        text = text.strip().lower()
        
        # Detect database type
        db_type = "postgres"
        if "mysql" in text:
            db_type = "mysql"
        elif "sqlite" in text:
            db_type = "sqlite"
        elif "mongo" in text or "nosql" in text:
            db_type = "mongodb"
        
        # Detect action
        action = "schema"
        if "migration" in text or "migracja" in text:
            action = "migration"
        elif "seed" in text or "dane testowe" in text:
            action = "seed"
        
        # Extract table names
        tables = self._extract_tables(text)
        
        return {
            "db_type": db_type,
            "action": action,
            "tables": tables,
            "description": text
        }
    
    def _extract_tables(self, text: str) -> List[str]:
        """Ekstraktuje nazwy tabel z tekstu"""
        
        keywords = ["users", "user", "products", "product", "orders", "order", 
                   "customers", "customer", "items", "categories", "posts"]
        
        found = []
        for keyword in keywords:
            if keyword in text:
                # Pluralize
                table = keyword + "s" if not keyword.endswith("s") else keyword
                if table not in found:
                    found.append(table)
        
        return found if found else ["users", "products"]
    
    def generate_command(self, intent: Dict[str, Any]) -> str:
        """Generuje schemat lub migrację"""
        
        db_type = intent["db_type"]
        action = intent["action"]
        tables = intent["tables"]
        
        if action == "schema":
            return self._generate_schema(db_type, tables)
        elif action == "migration":
            return self._generate_migration(db_type, tables)
        elif action == "seed":
            return self._generate_seed(db_type, tables)
        
        return "-- Database code"
    
    def _generate_schema(self, db_type: str, tables: List[str]) -> str:
        """Generuje schemat bazy danych"""
        
        if db_type in ["postgres", "mysql", "sqlite"]:
            return self._generate_sql_schema(db_type, tables)
        elif db_type == "mongodb":
            return self._generate_mongo_schema(tables)
        
        return "-- Schema"
    
    def _generate_sql_schema(self, db_type: str, tables: List[str]) -> str:
        """Generuje SQL schema"""
        
        schema = f"-- Database Schema ({db_type})\n"
        schema += f"-- Generated by NLP2CMD\n\n"
        
        for table in tables:
            schema += self._generate_table_schema(db_type, table)
            schema += "\n"
        
        # Add indexes
        schema += "\n-- Indexes\n"
        for table in tables:
            schema += f"CREATE INDEX idx_{table}_created_at ON {table}(created_at);\n"
        
        return schema
    
    def _generate_table_schema(self, db_type: str, table: str) -> str:
        """Generuje schemat pojedynczej tabeli"""
        
        # Common tables with standard fields
        if "user" in table:
            return f'''-- {table.capitalize()} table
CREATE TABLE {table} (
    id {self._get_id_type(db_type)} PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
'''
        
        elif "product" in table:
            return f'''-- {table.capitalize()} table
CREATE TABLE {table} (
    id {self._get_id_type(db_type)} PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock_quantity INTEGER DEFAULT 0,
    sku VARCHAR(50) UNIQUE,
    category_id INTEGER REFERENCES categories(id),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
'''
        
        elif "order" in table:
            return f'''-- {table.capitalize()} table
CREATE TABLE {table} (
    id {self._get_id_type(db_type)} PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    total_amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    shipping_address TEXT,
    payment_method VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
'''
        
        else:
            # Generic table
            return f'''-- {table.capitalize()} table
CREATE TABLE {table} (
    id {self._get_id_type(db_type)} PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
'''
    
    def _get_id_type(self, db_type: str) -> str:
        """Zwraca typ ID dla danej bazy"""
        if db_type == "postgres":
            return "SERIAL"
        elif db_type == "mysql":
            return "INT AUTO_INCREMENT"
        else:  # sqlite
            return "INTEGER"
    
    def _generate_mongo_schema(self, collections: List[str]) -> str:
        """Generuje Mongoose schemas dla MongoDB"""
        
        schema = "// MongoDB Schemas (Mongoose)\n"
        schema += "// Generated by NLP2CMD\n\n"
        schema += "const mongoose = require('mongoose');\n\n"
        
        for collection in collections:
            schema += self._generate_mongoose_model(collection)
            schema += "\n"
        
        return schema
    
    def _generate_mongoose_model(self, collection: str) -> str:
        """Generuje Mongoose model"""
        
        singular = collection.rstrip('s')
        model_name = singular.capitalize()
        
        if "user" in collection:
            return f'''// {model_name} Schema
const {singular}Schema = new mongoose.Schema({{
  email: {{
    type: String,
    required: true,
    unique: true,
    lowercase: true,
    trim: true
  }},
  username: {{
    type: String,
    required: true,
    unique: true,
    trim: true
  }},
  password: {{
    type: String,
    required: true
  }},
  firstName: String,
  lastName: String,
  isActive: {{
    type: Boolean,
    default: true
  }},
  isAdmin: {{
    type: Boolean,
    default: false
  }}
}}, {{
  timestamps: true
}});

module.exports = mongoose.model('{model_name}', {singular}Schema);
'''
        
        elif "product" in collection:
            return f'''// {model_name} Schema
const {singular}Schema = new mongoose.Schema({{
  name: {{
    type: String,
    required: true
  }},
  description: String,
  price: {{
    type: Number,
    required: true,
    min: 0
  }},
  stockQuantity: {{
    type: Number,
    default: 0,
    min: 0
  }},
  sku: {{
    type: String,
    unique: true
  }},
  category: {{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Category'
  }},
  isActive: {{
    type: Boolean,
    default: true
  }}
}}, {{
  timestamps: true
}});

module.exports = mongoose.model('{model_name}', {singular}Schema);
'''
        
        else:
            return f'''// {model_name} Schema
const {singular}Schema = new mongoose.Schema({{
  name: {{
    type: String,
    required: true
  }},
  description: String
}}, {{
  timestamps: true
}});

module.exports = mongoose.model('{model_name}', {singular}Schema);
'''
    
    def _generate_migration(self, db_type: str, tables: List[str]) -> str:
        """Generuje migration"""
        
        if db_type in ["postgres", "mysql"]:
            migration = f"-- Migration: Create {', '.join(tables)}\n"
            migration += "-- Up\n\n"
            migration += self._generate_sql_schema(db_type, tables)
            migration += "\n\n-- Down\n\n"
            
            for table in tables:
                migration += f"DROP TABLE IF EXISTS {table} CASCADE;\n"
            
            return migration
        
        elif db_type == "mongodb":
            return f'''// MongoDB Migration
// Create collections and indexes

const migrations = {{
  async up(db) {{
    // Create collections
    {chr(10).join([f"await db.createCollection('{table}');" for table in tables])}
    
    // Create indexes
    {chr(10).join([f"await db.collection('{table}').createIndex({{ createdAt: 1 }});" for table in tables])}
  }},
  
  async down(db) {{
    // Drop collections
    {chr(10).join([f"await db.collection('{table}').drop();" for table in tables])}
  }}
}};

module.exports = migrations;
'''
        
        return "-- Migration"
    
    def _generate_seed(self, db_type: str, tables: List[str]) -> str:
        """Generuje seed data"""
        
        if db_type in ["postgres", "mysql", "sqlite"]:
            seed = f"-- Seed Data\n\n"
            
            for table in tables:
                seed += f"-- {table.capitalize()}\n"
                
                if "user" in table:
                    seed += f'''INSERT INTO {table} (email, username, password_hash, first_name, last_name) VALUES
  ('admin@example.com', 'admin', '$2b$10$hash', 'Admin', 'User'),
  ('john@example.com', 'john', '$2b$10$hash', 'John', 'Doe'),
  ('jane@example.com', 'jane', '$2b$10$hash', 'Jane', 'Smith');

'''
                
                elif "product" in table:
                    seed += f'''INSERT INTO {table} (name, description, price, stock_quantity, sku) VALUES
  ('Product 1', 'Description 1', 29.99, 100, 'SKU001'),
  ('Product 2', 'Description 2', 49.99, 50, 'SKU002'),
  ('Product 3', 'Description 3', 19.99, 200, 'SKU003');

'''
            
            return seed
        
        elif db_type == "mongodb":
            return '''// MongoDB Seed Data
const seedData = {
  users: [
    {
      email: 'admin@example.com',
      username: 'admin',
      password: 'hashed_password',
      isAdmin: true
    },
    {
      email: 'john@example.com',
      username: 'john',
      password: 'hashed_password'
    }
  ],
  products: [
    {
      name: 'Product 1',
      description: 'Description 1',
      price: 29.99,
      stockQuantity: 100
    },
    {
      name: 'Product 2',
      description: 'Description 2',
      price: 49.99,
      stockQuantity: 50
    }
  ]
};

module.exports = seedData;
'''
        
        return "-- Seed data"
    
    def execute(self, text: str) -> ConversionResult:
        """
        Generuje schemat bazy danych.
        
        Args:
            text: Opis bazy w języku naturalnym
            
        Returns:
            Wynik z wygenerowanym schematem
        """
        try:
            intent = self.parse_intent(text)
            code = self.generate_command(intent)
            
            return ConversionResult(
                success=True,
                command=f"Generated {intent['action']} for {intent['db_type']}",
                output=code,
                metadata={
                    "db_type": intent["db_type"],
                    "action": intent["action"],
                    "tables": intent["tables"]
                }
            )
            
        except Exception as e:
            logger.error(f"Błąd generowania: {e}")
            return ConversionResult(
                success=False,
                error=str(e),
                metadata={"input": text}
            )
    
    def save_schema(
        self,
        code: str,
        db_type: str,
        directory: str = "database"
    ) -> bool:
        """
        Zapisuje schemat do pliku.
        
        Args:
            code: Kod schematu
            db_type: Typ bazy danych
            directory: Katalog docelowy
            
        Returns:
            True jeśli sukces
        """
        try:
            path = Path(directory)
            path.mkdir(parents=True, exist_ok=True)
            
            # Determine extension
            if db_type == "mongodb":
                ext = ".js"
            else:
                ext = ".sql"
            
            # Save schema
            schema_file = path / f"schema{ext}"
            schema_file.write_text(code)
            
            logger.info(f"Zapisano schemat w: {directory}")
            return True
            
        except Exception as e:
            logger.error(f"Błąd zapisu: {e}")
            return False
